services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - VERSION=docker
      - PLEX_CLAIM=
    volumes:
      - /home/adam/plexconfig:/config
      - /mnt/poolmedia/Series:/tv
      - /mnt/poolmedia/Movies:/movies
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
